// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef DUMMY_REGS_H
#define DUMMY_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - dummy_regs::control
#define DUMMY_REGS__CONTROL__SW_BIT_bm 0x1
#define DUMMY_REGS__CONTROL__SW_BIT_bp 0
#define DUMMY_REGS__CONTROL__SW_BIT_bw 1
#define DUMMY_REGS__CONTROL__SW_BIT_reset 0x0

// reg - dummy_regs::status
#define DUMMY_REGS__STATUS__HW_BIT_bm 0x1
#define DUMMY_REGS__STATUS__HW_BIT_bp 0
#define DUMMY_REGS__STATUS__HW_BIT_bw 1
#define DUMMY_REGS__STATUS__HW_BIT_reset 0x0

// addrmap - dummy_regs
typedef struct __attribute__ ((__packed__)) {
    uint32_t control;
    uint32_t status;
} dummy_regs_t;


static_assert(sizeof(dummy_regs_t) == 0x8, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* DUMMY_REGS_H */
