// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package dummy_regs_pkg;

    localparam DUMMY_REGS_DATA_WIDTH = 32;
    localparam DUMMY_REGS_MIN_ADDR_WIDTH = 12;
    localparam DUMMY_REGS_SIZE = 'h8;

    typedef struct {
        logic next;
        logic we;
    } dummy_regs__status__hw_bit__in_t;

    typedef struct {
        dummy_regs__status__hw_bit__in_t hw_bit;
    } dummy_regs__status__in_t;

    typedef struct {
        dummy_regs__status__in_t status;
    } dummy_regs__in_t;

    typedef struct {
        logic value;
    } dummy_regs__control__sw_bit__out_t;

    typedef struct {
        dummy_regs__control__sw_bit__out_t sw_bit;
    } dummy_regs__control__out_t;

    typedef struct {
        dummy_regs__control__out_t control;
    } dummy_regs__out_t;
endpackage
